"""Add latest column to MACH_Employee

Revision ID: fcac03c81619
Revises: 
Create Date: 2024-06-13 12:53:01.577739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcac03c81619'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mach_employee', sa.Column('latest', sa.Boolean, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mach_employee', 'latest')
    # ### end Alembic commands ###
